// <auto-generated />
using System;
using ColorApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ColorApplication.Migrations.ColorPallet
{
    [DbContext(typeof(ColorPalletContext))]
    [Migration("20210405010402_inti")]
    partial class inti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ColorApplication.Models.ColorPallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pallet")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ColorPallet");
                });
#pragma warning restore 612, 618
        }
    }
}
